


function mye(){
    let salam= document.querySelector(".heder");
let arr =["Wer ist die verrückteste Person, die du kennst?"," Was war das Verrückteste, das du zufällig mitgehört hast?","Wie lang war deine längste duschfreie Zeit?","Wenn du für den Rest deines Lebens nur mehr einer einzigen Person schreiben dürftest, wer wäre es? Es gibt nur einen Haken – du dürftest mit der Person nie wieder von Angesicht zu Angesicht reden!"," Was ist passiert, als du versehentlich der falschen Person eine peinliche Nachricht geschickt hast? Beschreibe die Situation!","Was ist deine ekelhafteste Angewohnheit?","Wie lange war deine längste Phase ohne Zähneputzen?"," Kannst du den Refrain deiner Lieblingsschnulze singen?","Welche Sache würdest du am liebsten ungesehen machen?","Was würdest du nie beim ersten Date essen?","Was ist das erste Wort, das dir gerade einfällt?"," Wenn du dein Geschlecht für einen Tag wechseln könntest, was würdest du dann machen?"," Was sind die positiven Eigenschaften der Person, die du am meisten hasst?","Was wäre das schlimmste Wetter, um draußen ausgesperrt zu sein, wenn du nur einen Badeanzug tragen würdest?","Wenn du ein Gedicht über deinen Chef schreiben müsstest, wie würde es lauten?","Wenn du eine Autopanne mitten auf dem Weg hättest, wen in diesem Raum würdest du als Letztes anrufen und warum?","Was ist das unnötigste Wissen, das du hast?"," Welches war dein schrecklichstes Vorstellungsgespräch, das du bisher hattest?","Wenn du ein Tier daten müsstest, welche Tierart wäre es?","Was hast du in der Schule gelernt, was du am liebsten vergessen würdest?","Wer war die letzte Person, die du in den sozialen Netzwerken gestalkt hast?","Wenn du eine Pflanze daten müsstest, welche Pflanzenart wäre es und warum?","Ist es besser Shampoo als Seife oder Seife als Shampoo zu verwenden?","Welche war die verrückteste Veranstaltung, die du je besucht hast?","Wenn du einen deiner Lehrer daten würdest, wer wäre es?"," Wenn dir das Klopapier ausgehen würde, würdest du dich dazu entschließen, die leere Rolle zu verwenden?","Was war dein peinlichstes Erlebnis dieses Jahr?","Was würdest du tun, wenn dir in einer öffentlichen Toilette das Klopapier ausgeht, nachdem du ein großes Geschäft verrichtet hast?","Mit wem in diesem Raum würdest du deiner Meinung nach dein schlimmstes Date haben?","Was war das Peinlichste, das dir in der Öffentlichkeit passiert ist?"]
     var randomIndex = Math.floor(Math.random() * arr.length);
    salam.innerHTML=arr[randomIndex]
    console.log(randomIndex)
}

function my2(){
    let salam= document.querySelector(".heder2");
    let arr2 =["Spreche für die nächsten drei Runden mit einem Akzent","Mache einen Screenshot von deinem Browserverlauf und schicke es deinen Eltern.","Geh hinaus und tanze wie ein Cowboy.","Unterhalte uns mit deinem besten 5-Minuten-Comedyauftritt.","Versuche 30 Sekunden lang einen Breakdance hinzulegen.","Ruf ein chinesisches Restaurant an und bestell eine Pizza."," Gib der Person neben dir einen Klaps auf den Po.","Geh für einen kurzen Spaziergang hinaus und führe währenddessen Selbstgespräche.","Verkleide dich wie ein Mann, mach ein Foto und schicke es deinen Eltern.","Gib Schokoladensirup auf eine Essiggurke und iss sie.","Mumifiziere dich mit so viel Toilettenpapier, wie du nur finden kannst.","Ruf eine x-beliebige Person an und singe ihr ein Lied vor."," Frage ein Haustier nach einem Date, ohne dabei in Lachen auszubrechen oder zu grinsen.","Ruf die Eltern von jemandem aus der Gruppe an. Erkläre ihnen, warum du ihr Kind so sehr liebst und leg ohne Grund wieder auf.","Stecke dir 4 Eiswürfel in die Unterhose.","Jungs: Trage Make-up. Mädels: (Entferne dein Make-up(Keine Panik Jungs))","Tanze eine Minute lang ohne Musik."," Lass dich von der Gruppe in eine peinliche Position bringen und fotografieren."," Spiele deinen Eltern einen Telefonstreich."," Die Person links von dir soll dir mit einem Stift etwas ins Gesicht malen.","Iss eine Handvoll trockene Nudeln.","Denk dir eine 30-sekündige Oper über eine Person oder jemanden aus der Gruppe aus und performe sie.","Gib dir einen Klecks Erdnussbutter auf die Nase und versuche sie abzuschlecken","Halte ein Restaurant 5 Minuten lang in der Leitung. Sprich mit britischem Akzent und storniere die Bestellung in letzter Sekunde."," Steh auf einem Bein und belle zwei Minuten lang, während du mit den Armen wie ein Huhn flatterst.","Flirte mit dir selbst im Spiegel","Gehe auf deinen Händen von einem Ende des Raums zum anderen. Wenn nötig, kannst du jemanden um Hilfe bitten, deine Beine dabei zu halten.","Für den Rest des Spiels quake wie eine Ente, bevor du sprichst.","Gib dein Bestes als ein Pantomime, der in einer Box feststeckt.","Drehe dich 10-mal und sprinte dann 15 m vorwärts.","Benimm dich wie ein 80-jähriger Mann ganze zwei Minuten lang.","Lauf auf der Stelle und miaue dabei zwei Minuten lang.","Stell dir etwas im Raum vor. Versuche es mit deiner Nase zu buchstabieren. Mach so lange weiter, bis es jemand aus der Gruppe errät.","Schütte dir eine volle Tasse Mehl über den Kopf."]
     var randomIndex2 = Math.floor(Math.random() * arr2.length);
    salam.innerHTML=arr2[randomIndex2]
    console.log(randomIndex2)
}
 
